### ISSUE TITLE
Support centered text

### ISSUE THREAD

**Issue by farazahmed7** [airbnb/lottie-android#388]
I am testing with a simple text layer but the alignment of the text is different in lottie app from the preview in after effects. I haven't done any changes to a new project expect for a text layer
I am attaching screenshots and json file

Ae preview 
![capture](https://user-images.githubusercontent.com/1413332/28283651-f93445ba-6b4b-11e7-8adb-f27b02b6f1fc.PNG)

in lottie app

![screenshot_2017-07-17-23-53-34-559_com airbnb lottie](https://user-images.githubusercontent.com/1413332/28283754-650b344c-6b4c-11e7-8661-f00ff9074d8c.png)

As you can see the text is aligned differently on app 
json
[data.zip](https://github.com/airbnb/lottie-android/files/1153634/data.zip)

**Comment by tehfailsafe** [comment]
I am having the same problem, looks perfect the bodymovin JS player web version, but on android everything is shifted over to the right (but correct vertical alignment)

**Comment by ijunes** [comment]
same here... i was able to modify some values in the json and get them to render correctly, but the additional "padding" was also added to the js web player

**Comment by luciancioroga** [comment]
Same here. I'm trying now with bodymovin 4.11.1 and lottie 2.2.5. Basically, what AE and bodymovin considers the center of the text, lottie considers the bottom left corner as far as I can tell.

**Comment by mammademin** [comment]
I have same issue.It looks perfect in AE but not when I render it with bodymovin. Any idea how we can solve this issue?

**Comment by skinnypojo** [comment]
same issue, any solution?

**Comment by RoyGuanyu** [comment]
Same issue here, any update?

**Comment by perky** [comment]
I can reproduce this bug:

1. Create a text layer in AE by selecting Layer/New/Text.
2. Create another text layer by selecting the Horizontal Type Tool and dragging a text box in the composition.
3. Position both text layers so that they are aligned.

When you render via bodymovin you will see that the 2nd text layer has been shifted to the right and is now out of alignment with the 1st layer.

**AE Version:** 15.0.0 (Build 180)
**Bodymovin Version:** 5.1.3

**Comment by mxia** [comment]
Any update on this and #481 (seems to be a duplicate)? Or any suggestion on how to work around the issue is greatly appreciated too!

**Comment by karanmintzip** [comment]
RESOLVED: You need to convert text to Shape in order to render the text correctly.

**Comment by TacB0sS** [comment]
Not a solution... text mostly is dynamic and should be rendered on the fly

**Comment by karanmintzip** [comment]
Re: @TacB0sS But it's not rendering with proper allignment as a text. It worked for me after converting to shape.

**Comment by TacB0sS** [comment]
True, this solves the problem.. but it is not a solution for the bug.. they have a bug and it needs a real fix

**Comment by farazfaraz** [comment]
Converting text to shape just defeats the purpose of text feature. Plus the size also increases a lot.

Guys instead of dragging text box from tools to the canvas, just double click on text icon. And then start typing in the text box. Then you can move it to your desired place in the canvas. Ik its pretty weird but this way my alignment was fixed when I last tried it

**Comment by zishanj** [comment]
I am still facing alignment issue with lottie 3.0.1

```
<com.airbnb.lottie.LottieAnimationView
            android:id="@+id/completed_animation_view"
            app:lottie_fileName="topic_completed.json"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_gravity="center"
            android:scaleType="centerInside"
            android:visibility="@{viewModel.isCompleted ? View.VISIBLE : View.GONE}"
            tools:visibility="visible"/>
```
result:

![image](https://user-images.githubusercontent.com/1451292/58481264-7e33ee00-8175-11e9-981c-b4f3fdcdb7e7.png)

I have tried with `centerCrop` also but there is no effect on alignment. The complete text is _you have taken one step ahead_, but it get cropped due to misalignment. On web it appears perfectly, even if I minimize the browser, the width get auto adjusted and there is not misalignment of text.

**Comment by chanjungkim** [comment]
What's the solution???

**Comment by Pitel** [comment]
IMHO still not fixed!

Chnaging the texts to shapes is a woekartound at best. But we still had to do that.

**Comment by crackjack** [comment]
unlike everyone here, I'm actually seeing left aligned text, but this must be related

**Comment by sherrychen1202** [comment]
> RESOLVED: You need to convert text to Shape in order to render the text correctly.

This solves my problem.

**Comment by JahnKoutrios** [comment]
we are facing the same issue currently. has no one ever found any (even hacky) solution to this problem (except for converting to shape)?

**Comment by aishang5wpj** [comment]
you can convert your text to an image in code, then use setImageAssetDelegate to replace the it

**Comment by samiam2020** [comment]
@gpeal has a solution for the alignment of dynamic text been arrived at for android? We need the text to be editable in code, so the create outlines option won't work in this context.

**Comment by crackjack** [comment]
I actually gave up, and moved to a native textview.

Instead of having text within animation, it is in a textview. Sure does not have the same flexibility of just dropping your animation to xm, but with Lottie providing current frame, we can time the conditions to show/hide/replace text in the textview.

**Comment by taurelas** [comment]
Ensure that the "j" value for the text in JSON is 2 (centered)

**Comment by MrGVSV** [comment]
Why is this issue closed? The only solutions here are workarounds that remove the ability to dynamically change the text (for localization).

I'm facing the same issue— centered text gets moved all the way to the left.

**Comment by ursusursus** [comment]
I also face this issue. What's the solution?

**Comment by KohmM** [comment]
I solved this by using LottieProperty.TRANSFORM_ANCHOR_POINT and moving the text that way. I was using Lottie-compose.

```
rememberLottieDynamicProperty(
            property = LottieProperty.TRANSFORM_ANCHOR_POINT,
            value = PointF(0f, -85f),
            keyPath = arrayOf("BoxNameLayer")
        )
```
